# Generated by Django 3.1.2 on 2020-10-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
    ]
