# Generated by Django 3.1.3 on 2020-11-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('siren', 'Сирена'), ('speaker', 'Громкоговоритель')], max_length=50, verbose_name='Тип устройства'),
        ),
    ]
